# Generated by Django 5.0.1 on 2024-02-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='AboutIMG')),
                ('quantity', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='AboutMeIMG')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='BannerIMG')),
                ('title', models.CharField(max_length=255)),
                ('mid_title', models.CharField(max_length=255)),
                ('typ_education', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=5, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='FacultyIMG')),
            ],
        ),
        migrations.CreateModel(
            name='UnivGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='UnivGalleryIMG')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='UniversityIMG')),
                ('banner', models.ImageField(upload_to='UniversityBanner')),
                ('address', models.CharField(max_length=255)),
                ('about', models.FileField(upload_to='UniversityIMG')),
                ('rating', models.IntegerField(max_length=255)),
                ('price', models.DecimalField(decimal_places=5, max_digits=7)),
                ('process', models.CharField(max_length=255)),
                ('control', models.CharField(max_length=255)),
                ('motto', models.CharField(max_length=255)),
                ('degree', models.ManyToManyField(blank=True, null=True, to='main.degree')),
                ('faculty', models.ManyToManyField(to='main.faculty')),
                ('gallery', models.ManyToManyField(to='main.univgallery')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='StudentIMG')),
                ('degree', models.CharField(max_length=255)),
                ('passport', models.FileField(upload_to='StudentPassport')),
                ('certificate', models.FileField(upload_to='StudentCertificate')),
                ('ielts', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.faculty')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.university')),
            ],
        ),
    ]
