# Generated by Django 5.0.1 on 2024-02-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_university_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
