# Generated by Django 5.0.1 on 2024-02-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_degree_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='price',
            field=models.IntegerField(),
        ),
    ]
