# Generated by Django 5.0.1 on 2024-02-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_degree_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='price',
        ),
    ]
