# Generated by Django 5.0.1 on 2024-02-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='languages',
            field=models.ManyToManyField(to='main.language'),
        ),
    ]
