# Generated by Django 5.0.1 on 2024-02-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_university_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='languages',
            field=models.ManyToManyField(to='main.language'),
        ),
    ]
