# Generated by Django 5.0.1 on 2024-02-09 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_student_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='languages',
        ),
        migrations.AddField(
            model_name='student',
            name='languages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.language'),
            preserve_default=False,
        ),
    ]
