# Generated by Django 5.0.1 on 2024-02-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_personalmeneger'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Man'), (2, 'Woman')], default=1),
        ),
    ]
