# Generated by Django 5.0.1 on 2024-02-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_submituniversity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submituniversity',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submituniversity',
            name='certificate',
            field=models.FileField(default=1, upload_to='Register/Certificate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submituniversity',
            name='passport',
            field=models.FileField(default=1, upload_to='RegisPast'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submituniversity',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
            preserve_default=False,
        ),
    ]
