# Generated by Django 5.0.1 on 2024-02-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_submituniversity_answer_submituniversity_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(1, 'accept document'), (2, 'closed document')], default=1),
            preserve_default=False,
        ),
    ]
